#!/bin/bash
#colorize commands
alias du="du -csh"
alias dua="du -csh .[!.]* * |sort -h"
alias df="df -Th"
alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"
alias diff="colordiff -ru"
alias dmesg="dmesg --color"
alias tree="tree -Csh"
alias ip="ip -color=auto"

lsflags="-h -F --color=auto --group-directories-first"
alias l="\ls ${lsflags}"
alias ls="\ls -1 ${lsflags}"
alias la="\ls -lA ${lsflags}"
alias ll="\ls -1A ${lsflags}"
alias lr="\ls -R ${lsflags}"
alias lar="\ls -AR ${lsflags}"
alias lx="\ls -XB ${lsflags}"
alias llx="\ls -1XB ${lsflags}"
alias lax="\ls -1AXB ${lsflags}"


shopt -s autocd
alias ...="cd ../.."
alias ....="cd ../../.."
alias -- -="cd - > /dev/null"
alias dl="cd ~/Downloads"
alias dc="cd ~/Documents"
alias dots="cd ~/.dotfiles"
alias calc="python3 -ic \"from math import *; import cmath\""
alias pyshare="ip -j a| jq -r '.[].addr_info|.[].local|\"http://\"+.+\":8880\"' && python3 -m http.server 8880"
alias urlencode='python3 -c "import urllib.parse, sys; print(urllib.parse.quote(sys.argv[1] if len(sys.argv) > 1 else sys.stdin.read()[0:-1]))"'
alias urldecode='python3 -c "import urllib.parse, sys; print(urllib.parse.unquote(sys.argv[1] if len(sys.argv) > 1 else sys.stdin.read()[0:-1]))"'
alias g="git"
alias :q="exit"
alias h="history 50"
alias myip="curl ipinfo.io"

alias firescrot="adb shell screencap -p | feh -"
alias feh='feh --quiet --verbose'
alias feho='feh -Tviewer'

[ "$TERM" = "xterm-kitty" ] && alias ssh="kitty +kitten ssh"

# vim: ft=sh
