#!/bin/bash
#colorize commands
alias du="du -csh"
alias dua="du -csh .[!.]* * |sort -h"
alias df="df -Th"
alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"
alias diff="colordiff -ru"
alias dmesg="dmesg --color"
alias tree="tree -Csh"
alias ip="ip -color=auto"

alias ls="ls -h -F --color=auto --group-directories-first"
alias l="ls -l"
alias ll="ls -1"

alias la="ls -A"
alias lsa="ls -lA"
alias lla="ls -lA"

alias lr="ls -R"
alias lar="ls -AR"
alias llr="ls -lAR"

alias nv=nvim

function vh() {
	vim -c "help $* | only"
}

function info() {
	/usr/bin/info --output - --subnodes "$*" | sed '/^File: .*info/d' | less
}

alias pacdiff="DIFFPROG='vim -d' pacdiff -s"

shopt -s autocd
alias ...="cd ../.."
alias ....="cd ../../.."
alias -- -="cd - > /dev/null"
alias dl="cd ~/Downloads"
alias dc="cd ~/Documents"
alias calc="python3 -ic \"from math import *; import cmath\""
alias pyshare="ip -j a| jq -r '.[].addr_info|.[].local|\"http://\"+.+\":8880\"' && python3 -m http.server 8880"
alias urlencode='python3 -c "import urllib.parse, sys; print(urllib.parse.quote(sys.argv[1] if len(sys.argv) > 1 else sys.stdin.read()[0:-1]))"'
alias urldecode='python3 -c "import urllib.parse, sys; print(urllib.parse.unquote(sys.argv[1] if len(sys.argv) > 1 else sys.stdin.read()[0:-1]))"'
alias g="git"
alias :q="exit"
alias h="history 50"
alias myip="curl ipinfo.io"

alias firescrot="adb shell screencap -p | feh -"
alias feh='feh --quiet --verbose'
alias feho='feh -Tviewer'

[ "$TERM" = "xterm-kitty" ] && alias ssh="kitty +kitten ssh"

# vim: ft=sh
