#!/bin/bash
#export TERM='rxvt-unicode-256color'
#export COLORTERM='rxvt-unicode-256color'

export TERMINAL='kitty'
export TERM='kitty'
export VISUAL='nvim'
export EDITOR='nvim'

if [ -n "$DISPLAY" ]; then
	export BROWSER='firefox --private'
else
	export BROWSER='links'
fi

export HISTCONTROL="ignorespace:ignoredups:erasedups"
export HISTTIMEFORMAT="[%F %T] "
export HISTSIZE=999999
export HISTFILESIZE=$HISTSIZE;
export HISTIGNORE="ls:l:la:ll:cd:cd -:-:cd /tmp*:tmpd*:n.:pwd:exit:\:q:date:history:history :h:vim:vi:v"

export LS_COLORS="di=36;40:ln=35;40:so=31;:pi=0;:ex=1;;40:bd=0;:cd=37;:su=37;:sg=0;:tw=0;:ow=0;:"

export LESS='-RFiJWX --incsearch --use-color -Dd+g$Du+m'

export MANPAGER='nvim +Man!'

export PATH=$HOME/.bin:$HOME/.riscv/bin:$PATH
export WEECHAT_HOME=$HOME/.config/weechat

export LIBVA_DRIVER_NAME=nvidia
export MOZ_DISABLE_RDD_SANDBOX=1

unset SSH_AGENT_PID
export SSH_AUTH_SOCK=${XDG_RUNTIME_DIR}/gnupg/S.gpg-agent.ssh
#export GPG_TTY=$(tty)
#gpg-connect-agent updatestartuptty /bye >/dev/null

# vim: ft=sh
