#!/bin/bash

mkd () {
	mkdir -p -- "$1" && cd -P -- "$1"
}

tmpd() {
	local dir
	if [ $# -eq 0 ]; then
		dir=$(mktemp -d)
	else
		dir=$(mktemp -d --tmpdir "${1}.XXXXXXXXXX")
	fi
	cd "$dir" || exit
}

# Determine size of a file or total size of a directory
fs() {
	if [[ $# -ne 0 ]]; then
		du -sbh -- "$@"
	else
		du -sbh -- .[^.]* *
	fi
}

function tre() {
	tree -aC -I '.git|node_modules|bower_components' --du --dirsfirst "$@" | less -N;
}

#Fetch PKGBUILD directly from repo
function getpkgbuild(){
	if [[ $# -eq 0 ]]; then
		return 1
		
	elif curl --fail "https://gitlab.archlinux.org/archlinux/packaging/packages/$1/-/raw/main/PKGBUILD" 2>/dev/null; then
		:
	else
		echo "Can't find requested PKDBUILD" >&2
		return 44
	fi
}

# REFS
# firefox corrupt mp4 bug: https://support.mozilla.org/en-US/questions/1316956
#                          https://bugzilla.mozilla.org/show_bug.cgi?id=1450137
# encode using vp9/webm with yuv420p pixel format:
#                          https://trac.ffmpeg.org/wiki/Encode/VP9#compatibility
record_window() {
	ffmpeg -f x11grab  \
		-window_id $(xwininfo | sed -n '/Window id/s/^.*id: \(\w\+\) ".*/\1/p') \
		-show_region 1 -region_border 5 -i :0.0  \
		-c:v libvpx-vp9 -lossless 1 -pix_fmt yuv420p \
		"$(date +%Y-%m-%d_%H-%M_%S).webm"
}

0x0() {
	if [[ $# -eq 1 ]]; then
		curl -i -F"file=@$*" 'https://0x0.st'
	else
		curl -i -F'file=@-' 'https://0x0.st'
	fi
}

# vim: ft=sh
