#!/bin/bash

mkd () {
	mkdir -p -- "$1" && cd -P -- "$1"
}

tmpd() {
	local dir
	if [ $# -eq 0 ]; then
		dir=$(mktemp -d)
	else
		dir=$(mktemp -d --tmpdir "${1}.XXXXXXXXXX")
	fi
	cd "$dir" || exit
}

# Determine size of a file or total size of a directory
fs() {
	if [[ $# -ne 0 ]]; then
		du -sbh -- "$@"
	else
		du -sbh -- .[^.]* *
	fi
}

function tre() {
	tree -aC -I '.git|node_modules|bower_components' --du --dirsfirst "$@" | less -N;
}

#Fetch PKGBUILD directly from repo
function getpkgbuild(){
	if [[ $# -eq 0 ]]; then
		return 1
	elif curl -L --fail "https://raw.githubusercontent.com/archlinux/svntogit-packages/packages/${1}/trunk/PKGBUILD" 2>/dev/null; then
		:
	elif curl -L --fail "https://raw.githubusercontent.com/archlinux/svntogit-community/packages/${1}/trunk/PKGBUILD" 2>/dev/null; then
		:
	else
		echo "Can't find requested PKDBUILD" >&2
		return 44
	fi
}

# vim: ft=sh
