#!/bin/bash

mkd () {
	mkdir -p -- "$1" && cd -P -- "$1"
}

tmpd() {
	local dir
	if [ $# -eq 0 ]; then
		dir=$(mktemp -d)
	else
		dir=$(mktemp -d --tmpdir "${1}.XXXXXXXXXX")
	fi
	cd "$dir" || exit
}

# Determine size of a file or total size of a directory
fs() {
	if [[ $# -ne 0 ]]; then
		du -sbh -- "$@"
	else
		du -sbh -- .[^.]* *
	fi
}

function tre() {
	tree -aC -I '.git|node_modules|bower_components' --du --dirsfirst "$@" | less -N;
}

#Fetch PKGBUILD directly from repo
function getpkgbuild(){
	if [[ $# -eq 0 ]]; then
		return 1
		
	elif curl --fail "https://gitlab.archlinux.org/archlinux/packaging/packages/$1/-/raw/main/PKGBUILD" 2>/dev/null; then
		:
	else
		echo "Can't find requested PKDBUILD" >&2
		return 44
	fi
}

# REFS
# ffmpeg capture x11 window: https://stackoverflow.com/a/63211279
# firefox corrupt mp4 bug: https://support.mozilla.org/en-US/questions/1316956 
#                          https://bugzilla.mozilla.org/show_bug.cgi?id=1450137
# encode using vp8/webm with yuv420p pixel format: https://trac.ffmpeg.org/wiki/Encode/VP9
record_window() {
	ffmpeg -f x11grab -framerate 25 \
		$(xwininfo \
			| gawk 'match($0, /-geometry ([0-9]+x[0-9]+).([0-9]+).([0-9]+)/, a) \
				{ print "-video_size " a[1] " -i +" a[2] "," a[3] }' \
		) \
		-c:v libvpx-vp9 -pix_fmt yuv420p "$(date +%Y-%m-%d_%H-%M_%S).webm"

}

0x0() {
	if [[ $# -eq 1 ]]; then
		curl -i -F"file=@$*" 'https://0x0.st'
	else
		curl -i -F'file=@-' 'https://0x0.st'
	fi
}

# vim: ft=sh
