#! /bin/bash
dunstctl set-paused true

i3lock -n -i ~/Pictures/lock.png -t --keylayout 2 -k --pass-media-keys \
--time-color=FFFFFFFF --date-color=FFFFFFFF --layout-color=FFFFFFFF \
--date-str="%A %d, %b %Y"

dunstctl set-paused false
