#!/bin/sh

if [ -f ~/.base16_theme ]; then
	base16_theme=$(basename -s .sh `readlink ~/.base16_theme`)
fi

if [ -n "$base16_theme" ]; then
	base16_i3_url="https://raw.githubusercontent.com/khamer/base16-i3/master/themes/"$base16_theme".config"
	config_colors=$(curl -f $base16_i3_url 2>/dev/null)
fi

if [ -n "$config_colors" ]; then
	cp ~/.config/i3/config ~/.config/i3/config.backup
	TMPFILE=`mktemp /tmp/i3conf.XXXXXXXXXX` || exit 1
	cat ~/.config/i3/config | sed -e '/#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#/,$d' > $TMPFILE
	cp $TMPFILE ~/.config/i3/config
	echo -e "#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#\n###Color variables autogenerated with $(basename "$0")\n###Source: $base16_i3_url" >>~/.config/i3/config
	(echo "$config_colors" | sed "/^##\ Base16/,/^$/d; /^#\ Basic\ bar/,/^}/d; /^#\ Basic\ color/d" 	&& echo -e "\n# vim: ft=i3") >>~/.config/i3/config
	exit 0
fi
exit 1
